spring:
    application:
        name: court-service
    datasource:
        url: ${DB_URL:jdbc:postgresql://localhost:5432/court_service}
        username: ${DB_USERNAME:}
        password: ${DB_PASSWORD:}
    jpa:
        hibernate:
            ddl-auto: validate
    server:
        port: 8081

